// <auto-generated />
using System;
using DGPub.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DGPub.Infra.Data.Migrations
{
    [DbContext(typeof(DGPubContext))]
    [Migration("20200714051758_StartDataBase")]
    partial class StartDataBase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DGPub.Domain.Items.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<decimal>("Price");

                    b.HasKey("Id");

                    b.ToTable("Item");

                    b.HasData(
                        new { Id = new Guid("e53890e8-3c5b-4343-987d-ff9ebb63edce"), Name = "Cerveja", Price = 5m },
                        new { Id = new Guid("09229e4c-5d04-410c-a0b1-eb064b3aed1b"), Name = "Conhaque", Price = 20m },
                        new { Id = new Guid("fd1a1612-50b2-44e8-8563-b4e51b27ff73"), Name = "Suco", Price = 50m },
                        new { Id = new Guid("f07ee6ea-2b64-4d41-b6e7-bb5a50d87329"), Name = "Água", Price = 70m }
                    );
                });

            modelBuilder.Entity("DGPub.Domain.Tabs.ItemTab", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("ItemId");

                    b.Property<int>("Quantity");

                    b.Property<Guid>("TabId");

                    b.Property<decimal>("UnitPrice");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("TabId");

                    b.ToTable("ItemTab");
                });

            modelBuilder.Entity("DGPub.Domain.Tabs.Tab", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CustomerName")
                        .IsRequired();

                    b.Property<bool>("Open");

                    b.HasKey("Id");

                    b.ToTable("Tab");
                });

            modelBuilder.Entity("DGPub.Domain.Tabs.ItemTab", b =>
                {
                    b.HasOne("DGPub.Domain.Items.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DGPub.Domain.Tabs.Tab", "Tab")
                        .WithMany("Items")
                        .HasForeignKey("TabId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
