// <auto-generated />
using System;
using DGPub.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DGPub.Infra.Data.Migrations
{
    [DbContext(typeof(DGPubContext))]
    partial class DGPubContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DGPub.Domain.Items.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<decimal>("Price");

                    b.HasKey("Id");

                    b.ToTable("Item");

                    b.HasData(
                        new { Id = new Guid("67ff90d7-c765-46a2-8511-fe49872c2bf4"), Name = "Cerveja", Price = 5m },
                        new { Id = new Guid("ea18353a-b01e-49a9-bac7-57434555b13f"), Name = "Conhaque", Price = 20m },
                        new { Id = new Guid("f8e898dc-bb78-46f5-b9d3-ea2bd4f3291f"), Name = "Suco", Price = 50m },
                        new { Id = new Guid("1aa699c2-9235-46c8-8f5d-eb463338849d"), Name = "Água", Price = 70m }
                    );
                });

            modelBuilder.Entity("DGPub.Domain.Tabs.ItemTab", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Discount");

                    b.Property<Guid>("ItemId");

                    b.Property<Guid>("TabId");

                    b.Property<decimal>("UnitPrice");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("TabId");

                    b.ToTable("ItemTab");
                });

            modelBuilder.Entity("DGPub.Domain.Tabs.Tab", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CustomerName")
                        .IsRequired();

                    b.Property<bool>("Open");

                    b.HasKey("Id");

                    b.ToTable("Tab");
                });

            modelBuilder.Entity("DGPub.Domain.Tabs.ItemTab", b =>
                {
                    b.HasOne("DGPub.Domain.Items.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DGPub.Domain.Tabs.Tab", "Tab")
                        .WithMany("Items")
                        .HasForeignKey("TabId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
