// <auto-generated />
using System;
using DGPub.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DGPub.Infra.Data.Migrations
{
    [DbContext(typeof(DGPubContext))]
    partial class DGPubContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5");

            modelBuilder.Entity("DGPub.Domain.Items.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Item");

                    b.HasData(
                        new
                        {
                            Id = new Guid("208be985-f429-48e5-8ea9-ec3966c87430"),
                            Name = "Cerveja",
                            Price = 5m
                        },
                        new
                        {
                            Id = new Guid("5ae2d0db-1ef3-40dc-ab9a-8b9ff9130565"),
                            Name = "Conhaque",
                            Price = 20m
                        },
                        new
                        {
                            Id = new Guid("8dbf9f09-f772-449f-83c6-a869517e9c79"),
                            Name = "Suco",
                            Price = 50m
                        },
                        new
                        {
                            Id = new Guid("7709e4e6-1c49-4e62-a266-383c5f1a74ff"),
                            Name = "Água",
                            Price = 70m
                        });
                });

            modelBuilder.Entity("DGPub.Domain.Tabs.ItemTab", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TabId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("TabId");

                    b.ToTable("ItemTab");
                });

            modelBuilder.Entity("DGPub.Domain.Tabs.Tab", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tab");
                });

            modelBuilder.Entity("DGPub.Domain.Tabs.ItemTab", b =>
                {
                    b.HasOne("DGPub.Domain.Items.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DGPub.Domain.Tabs.Tab", "Tab")
                        .WithMany("Items")
                        .HasForeignKey("TabId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
